import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { ToastProvider } from "@/components/ui/toast";
import { NavbarComponent } from "@/components/components-navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ToastProvider>
        <NavbarComponent />
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
          <Toaster />
        </body>
        <footer className="flex flex-wrap items-center justify-center py-8">
          <a
            href="https://vercel.com?utm_source=geist&utm_campaign=oss"
            target="_blank"
            rel="noopener noreferrer"
            className=""
          >
            <p className="text-xs capitalize tracking-[0.5rem]">
              POWERED BY ECODAIRY LABS
            </p>
          </a>
        </footer>
      </ToastProvider>
    </html>
  );
}
